### ISSUE TITLE
Key errors of run.neighborhoods.py

### ISSUE THREAD

**Issue by FatihSarigol** [broadinstitute/ABC-Enhancer-Gene-Prediction#114]
Hello, thank you for designing this powerful algorithm. I managed to run the entire pipeline using the example files without a problem, but when I run it on my files I am receiving this key error below. Some similar errors were posted before and I tried the suggestions including two branches **use_pysam** and **no_promoter_overlaps** and I believe the formats of my input files are identical as of the example files, except for the bam files. Could you please give me hint about what exactly the error is trying to tell me?

```
Traceback (most recent call last):
  File "src/run.neighborhoods.py", line 97, in <module>
    main(args)
  File "src/run.neighborhoods.py", line 93, in main
    processCellType(args)
  File "src/run.neighborhoods.py", line 69, in processCellType
    annotate_genes_with_features(genes = genes,
  File "/project/LaminA/ABC/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 86, in annotate_genes_with_features
    tss1kb = make_tss_region_file(genes, outdir, genome_sizes)
  File "/project/LaminA/ABC/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 117, in make_tss_region_file
    tss1kb = pr.gf.genome_bounds(tss1kb, sizes_pr).df[['Chromosome','Start','End','name','score','strand']]
  File "/home/CIBIV/fatihs44/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3767, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/CIBIV/fatihs44/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5877, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/CIBIV/fatihs44/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5938, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['Chromosome', 'Start', 'End', 'name', 'score', 'strand'], dtype='object')] are in the [columns]"

```

When I run it using this flag **--skip_gene_counts** it gives a different error which may contain a clue I failed to see:

```
Traceback (most recent call last):
  File "src/run.neighborhoods.py", line 97, in <module>
    main(args)
  File "src/run.neighborhoods.py", line 93, in main
    processCellType(args)
  File "src/run.neighborhoods.py", line 77, in processCellType
    load_enhancers(genes=genes_for_class_assignment,
  File "/project/LaminA/ABC/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 207, in load_enhancers
    enhancers = assign_enhancer_classes(enhancers, genes, tss_slop = tss_slop_for_class_assignment)
  File "/project/LaminA/ABC/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 249, in assign_enhancer_classes
    genes, promoters = get_class_pyranges(enh)
  File "/project/LaminA/ABC/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 232, in get_class_pyranges
    genic_enh = genic_enh.df[['symbol','uid']].groupby('uid',as_index=False).aggregate(lambda x: ','.join(list(set(x))))
  File "/home/CIBIV/fatihs44/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3767, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/CIBIV/fatihs44/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5877, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/CIBIV/fatihs44/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5938, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['symbol', 'uid'], dtype='object')] are in the [columns]"
```

Thanks a lot!

**Comment by FatihSarigol** [comment]
I tried several things and finally I think that this is caused by having chromosomes that start with a number, looks like the code is assigning chromosome names as variables which should result with an error in python

**Comment by atancoder** [comment]
i think the code best works when chromosomes follow the format: chr{number}.
