### ISSUE TITLE
KeyError: 'ABC.Score'

### ISSUE THREAD

**Issue by olechnwin** [broadinstitute/ABC-Enhancer-Gene-Prediction#193]
Hi,

I have the following error when running ABC with my own dataset and danio rerio genome. 
I've looked at issues with similar error but I think they are different. 
Can you please help me on how to fix this?

```
[Thu Feb 29 13:36:55 2024]
Finished job 1.
1 of 4 steps (25%) done
Select jobs to execute...

[Thu Feb 29 13:36:55 2024]
rule filter_predictions:
    input: /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsAllPutative.tsv.gz, /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsAllPutativeNonExpressedGenes.tsv.gz
    output: /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsFull_threshold0.02_self_promoter.tsv, /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsFull_threshold0.02_self_promoter.bedpe, /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictions_threshold0.02_self_promoter.tsv, /home/analysis/ABC-results/P3F/Predictions/GenePredictionStats_threshold0.02_self_promoter.tsv
    jobid: 8
    reason: Missing output files: /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsFull_threshold0.02_self_promoter.tsv; Input files updated by another job: /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsAllPutativeNonExpressedGenes.tsv.gz, /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsAllPutative.tsv.gz
    wildcards: biosample=P3F, threshold=0.02, separator=, other_flags=_self_promoter
    resources: tmpdir=/gpfs0/scratch/4745978, mem_mb=8000, mem_mib=7630

Traceback (most recent call last):
  File "/home/opt/miniconda3/envs/mamba_env/envs/abc-env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ABC.Score'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs0/home2/opt/ABC-Enhancer-Gene-Prediction/workflow/scripts/filter_predictions.py", line 75, in <module>
    main()
  File "/home/opt/miniconda3/envs/mamba_env/envs/abc-env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/opt/miniconda3/envs/mamba_env/envs/abc-env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/opt/miniconda3/envs/mamba_env/envs/abc-env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/opt/miniconda3/envs/mamba_env/envs/abc-env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/gpfs0/home2/opt/ABC-Enhancer-Gene-Prediction/workflow/scripts/filter_predictions.py", line 50, in main
    filtered_predictions = all_putative[all_putative[score_column] > threshold]
  File "/home/opt/miniconda3/envs/mamba_env/envs/abc-env/lib/python3.10/site-packages/pandas/core/frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/opt/miniconda3/envs/mamba_env/envs/abc-env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'ABC.Score'
[Thu Feb 29 13:36:56 2024]
Error in rule filter_predictions:
    jobid: 8
    input: /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsAllPutative.tsv.gz, /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsAllPutativeNonExpressedGenes.tsv.gz
    output: /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsFull_threshold0.02_self_promoter.tsv, /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsFull_threshold0.02_self_promoter.bedpe, /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictions_threshold0.02_self_promoter.tsv, /home/analysis/ABC-results/P3F/Predictions/GenePredictionStats_threshold0.02_self_promoter.tsv
    conda-env: /gpfs0/home2/opt/ABC-Enhancer-Gene-Prediction/.snakemake/conda/aac40421100b3c7f900cabf6c6e20729_
    shell:
        
		python workflow/scripts/filter_predictions.py 			--output_tsv_file /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsFull_threshold0.02_self_promoter.tsv 			--output_slim_tsv_file /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictions_threshold0.02_self_promoter.tsv 			--output_bed_file /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsFull_threshold0.02_self_promoter.bedpe 			--output_gene_stats_file /home/analysis/ABC-results/P3F/Predictions/GenePredictionStats_threshold0.02_self_promoter.tsv 			--pred_file /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsAllPutative.tsv.gz 			--pred_nonexpressed_file /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsAllPutativeNonExpressedGenes.tsv.gz 			--score_column ABC.Score 			--threshold 0.02 			--include_self_promoter True 			--only_expressed_genes False
		
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-02-29T133645.924324.snakemake.log

```

Thanks!

**Comment by atancoder** [comment]
Ah yes, when you don't provide HiC info, we end up using the power law. As a result, we don't fill out the `ABC.Score` column. We'll probably start filling out ABC.Score, even if power law is used in the next release

In your config, I would change the score column to `powerlaw.Score`: https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/blob/dev/config/config.yaml#L43.

**Comment by olechnwin** [comment]
Thank you so much for your quick reply.

Is there anything else I should change because I have another error:

```
[Thu Feb 29 14:32:17 2024]
rule generate_qc_plot_and_summary:
    input: /home/analysis/ABC-results/P3F/Peaks/macs2_peaks.narrowPeak.sorted.candidateRegions.bed, /home/analysis/ABC-results/P3F/Neighborhoods, /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsFull_threshold0.02_self_promoter.tsv, reference/danRer11/danRer11.chrom.sizes.tsv
    output: /home/analysis/ABC-results/P3F/Metrics/QCSummary_threshold0.02_self_promoter.tsv, /home/analysis/ABC-results/P3F/Metrics/QCPlots_threshold0.02_self_promoter.pdf
    jobid: 7
    reason: Missing output files: /home/analysis/ABC-results/P3F/Metrics/QCSummary_threshold0.02_self_promoter.tsv; Input files updated by another job: /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsFull_threshold0.02_self_promoter.tsv
    wildcards: biosample=P3F, threshold=0.02, separator=, other_flags=_self_promoter
    resources: tmpdir=/gpfs0/scratch/4745984, mem_mb=8000, mem_mib=7630

No protocol specified

Traceback (most recent call last):
  File "/home/opt/miniconda3/envs/mamba_env/envs/abc-env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'hic_contact'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs0/home2/opt/ABC-Enhancer-Gene-Prediction/workflow/scripts/grabMetrics.py", line 74, in <module>
    generateQCMetrics(args)
  File "/gpfs0/home2/opt/ABC-Enhancer-Gene-Prediction/workflow/scripts/grabMetrics.py", line 53, in generateQCMetrics
    HiCQC(prediction_df, args.hic_gamma, args.hic_scale, pdf_writer)
  File "/gpfs0/home2/opt/ABC-Enhancer-Gene-Prediction/workflow/scripts/metrics.py", line 214, in HiCQC
    PlotPowerLawRelationship(
  File "/gpfs0/home2/opt/ABC-Enhancer-Gene-Prediction/workflow/scripts/metrics.py", line 224, in PlotPowerLawRelationship
    df = df[df[y_axis_col] > 0]
  File "/home/opt/miniconda3/envs/mamba_env/envs/abc-env/lib/python3.10/site-packages/pandas/core/frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/opt/miniconda3/envs/mamba_env/envs/abc-env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'hic_contact'
[Thu Feb 29 14:32:20 2024]
Error in rule generate_qc_plot_and_summary:
    jobid: 7
    input: /home/analysis/ABC-results/P3F/Peaks/macs2_peaks.narrowPeak.sorted.candidateRegions.bed, /home/analysis/ABC-results/P3F/Neighborhoods, /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsFull_threshold0.02_self_promoter.tsv, reference/danRer11/danRer11.chrom.sizes.tsv
    output: /home/analysis/ABC-results/P3F/Metrics/QCSummary_threshold0.02_self_promoter.tsv, /home/analysis/ABC-results/P3F/Metrics/QCPlots_threshold0.02_self_promoter.pdf
    conda-env: /gpfs0/home2/opt/ABC-Enhancer-Gene-Prediction/.snakemake/conda/aac40421100b3c7f900cabf6c6e20729_
    shell:
        
		python workflow/scripts/grabMetrics.py 			--outdir /home/analysis/ABC-results/P3F/Metrics 			--output_qc_summary /home/analysis/ABC-results/P3F/Metrics/QCSummary_threshold0.02_self_promoter.tsv 			--output_qc_plots /home/analysis/ABC-results/P3F/Metrics/QCPlots_threshold0.02_self_promoter.pdf 			--macs_peaks /home/analysis/ABC-results/P3F/Peaks/macs2_peaks.narrowPeak.sorted.candidateRegions.bed 			--neighborhood_outdir /home/analysis/ABC-results/P3F/Neighborhoods 			--preds_file /home/analysis/ABC-results/P3F/Predictions/EnhancerPredictionsFull_threshold0.02_self_promoter.tsv 			--chrom_sizes reference/danRer11/danRer11.chrom.sizes.tsv 			--hic_gamma 1.024238616787792 			--hic_scale 5.9594510043736655 
		
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job generate_qc_plot_and_summary since they might be corrupted:
/home/analysis/ABC-results/P3F/Metrics/QCPlots_threshold0.02_self_promoter.pdf
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-02-29T143205.932307.snakemake.log
```

**Comment by atancoder** [comment]
Ah yes, it looks like that rule had assumed HiC data was provided. If you still want to generate QC plots, you can comment that line out: https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/blob/main/workflow/scripts/grabMetrics.py#L53.

Otherwise, you don't really need that rule and should have the prediction files you need
