### ISSUE TITLE
Error when using my own HiC data

### ISSUE THREAD

**Issue by LRizzardi1** [broadinstitute/ABC-Enhancer-Gene-Prediction#22]
Thank you so much for this useful pipeline. I've gotten it to work with the example data and provided average HiC data. However, I am now trying to use my own cell type-specific HiC data (starting with .hic file) and am getting an error when computing the powerlaw. The error is below when i try just with chr22 as a test (using v0.2.2):

```
Traceback (most recent call last):
  File "../src/compute_powerlaw_fit_from_hic.py", line 70, in load_hic_for_powerlaw
    interpolate_nan=False)
  File "../src/hic.py", line 52, in load_hic
    apply_diagonal_bin_correction = apply_diagonal_bin_correction)
  File "../src/hic.py", line 80, in process_hic
    assert(np.max(sums[sums > 0])/np.min(sums[sums > 0]) < 1.001)
AssertionError
Traceback (most recent call last):
  File "../src/compute_powerlaw_fit_from_hic.py", line 119, in <module>
    main()
  File "../src/compute_powerlaw_fit_from_hic.py", line 38, in main
    HiC = load_hic_for_powerlaw(args)
  File "../src/compute_powerlaw_fit_from_hic.py", line 100, in load_hic_for_powerlaw
    all_data = pd.concat(all_data_list)
  File "../lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 255, in concat
    sort=sort,
  File "../lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

**Comment by LRizzardi1** [comment]
There seems to have been an error with the .hic file.......i used another one I made and it worked fine. Closing this issue.
