### ISSUE TITLE
--hic_gamma and --hic_scale parameter for ENCFF621AIY.hic

### ISSUE THREAD

**Issue by L1angyan** [broadinstitute/ABC-Enhancer-Gene-Prediction#239]
Hi
I downloaded the K562 Hi-C result: [ENCFF621AIY.hic](https://www.encodeproject.org/files/ENCFF621AIY/) from ENCODE. 

Then I ran **juicebox_dump.py** for compute the **hic_gamma** and **hic_scale**. 

However, I got **Error reading datasetnull Could not read hic file: null** error.
I noticed that could be derived from the [different juicer version](https://groups.google.com/g/3d-genomics/c/7ZXsq-R9zjE).
Is there any juicer_tools version consistent with the **ENCFF621AIY.hic**?

Alternatively, in the create_predictions section of `snakemake -n -p` output, `--hic_gamma 1.024238616787792 --hic_scale 5.9594510043736655` was set. Is that appropriate setting for this dataset?

Best
Yan

**Comment by L1angyan** [comment]
Using another version of juicer_tools also got error.
```
python ABC-Enhancer-Gene-Prediction-1.1.2/workflow/scripts/juicebox_dump.py \
    --hic_file HiC/ENCFF621AIY.hic \
    --juicebox \"java -jar ~/software/juicer_tools_2.13.06.jar\" \
    --resolution 5000 \
    --outdir K562_intact_HiC
```

```
Invalid chromosome 1
Traceback (most recent call last):
  File "/public/home/liunangroup/liangyan/project/tf-assymmetry/20240823/3.TEE_function/ABC_model/ABC-Enhancer-Gene-Prediction-1.1.2/workflow/scripts/juicebox_dump.py", line 89, in <module>
    main(args)
  File "/public/home/liunangroup/liangyan/project/tf-assymmetry/20240823/3.TEE_function/ABC_model/ABC-Enhancer-Gene-Prediction-1.1.2/workflow/scripts/juicebox_dump.py", line 57, in main
    run_command(command)
  File "/public/home/liunangroup/liangyan/project/tf-assymmetry/20240823/3.TEE_function/ABC_model/ABC-Enhancer-Gene-Prediction-1.1.2/workflow/scripts/tools.py", line 18, in run_command
    return check_output(command, shell=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/liunangroup/liangyan/software/miniconda3/envs/abc-env/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/liunangroup/liangyan/software/miniconda3/envs/abc-env/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'java -jar ~/software/juicer_tools_2.13.06.jar dump observed KR HiC/ENCFF621AIY.hic 1 1 BP 5000 K562_intact_HiC/chr1/chr1.KRobserved' returned non-zero exit status 77.
```
