### ISSUE TITLE
Predictions needs chrY file without --includechrY

### ISSUE THREAD

**Issue by liesaweigert** [broadinstitute/ABC-Enhancer-Gene-Prediction#27]
I am running the predict.py script as follows:

python src/predict.py \
--enhancers Neighborhoods_Cortex/EnhancerList.txt \
--genes Neighborhoods_Cortex/GeneList.txt \
--HiCdir CHiP_HiC_input/Cortex_HiC \
--hic_resolution 10000 \
--scale_hic_using_powerlaw --threshold .02 --cellType Cortex --outdir Predictions_Cortex/ \
--make_all_putative

However, I get an error for chromosome Y, stating that the file is not found. Which makes sense, since I do not have the HiC Data for chrY. 

Making predictions for chromosome: Y
Making putative predictions table...
Using: CHiP_HiC_input/Cortex_HiC/chrY/chrY.VCobserved.gz
Begin HiC
Loading HiC
Traceback (most recent call last):
  File "src/predict.py", line 141, in <module>
    main()
  File "src/predict.py", line 103, in main
    this_chr = make_predictions(chromosome, this_enh, this_genes, args)
  File "/psycl/g/mpsziller/liesa/ABC-Enhancer-Gene-Prediction/src/predictor.py", line 14, in make_predictions
    pred = add_hic_to_enh_gene_table(enhancers, genes, pred, hic_file, hic_norm_file, hic_is_vc, chromosome, args)
  File "/psycl/g/mpsziller/liesa/ABC-Enhancer-Gene-Prediction/src/predictor.py", line 63, in add_hic_to_enh_gene_table
    gamma = args.hic_gamma)
  File "/psycl/g/mpsziller/liesa/ABC-Enhancer-Gene-Prediction/src/hic.py", line 38, in load_hic
    HiC_sparse_mat = hic_to_sparse(hic_file, hic_norm_file, hic_resolution)
  File "/psycl/g/mpsziller/liesa/ABC-Enhancer-Gene-Prediction/src/hic.py", line 146, in hic_to_sparse
    header=None, engine='c', memory_map=True)
  File "/u/liewe/conda-envs/bpnet/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/u/liewe/conda-envs/bpnet/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/u/liewe/conda-envs/bpnet/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/u/liewe/conda-envs/bpnet/lib/python3.6/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/u/liewe/conda-envs/bpnet/lib/python3.6/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 613, in pandas._libs.parsers.TextReader._setup_parser_source
  File "/u/liewe/conda-envs/bpnet/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'CHiP_HiC_input/Cortex_HiC/chrY/chrY.VCobserved.gz'

I thought that without the explicit flag, chromosome Y is not needed, as it is not computed?

**Comment by liesaweigert** [comment]
The issue was due to naming conventions (chrY vs Y) and could be easily resolved by adding a line in the predict.py script.
