### ISSUE TITLE
'neighborhoods.py' (line 448) ~> pandas dataframe size mismatch on assertion in function 'count_single_feature_for_bed'

### ISSUE THREAD

**Issue by neekonsu** [broadinstitute/ABC-Enhancer-Gene-Prediction#32]
Hello all.

I just finished debugging issue #25 , and with the success of that first leg of the pipeline, a new data processing error has emerged.

Everything before this error is successful, so I believe the reason for this new error is that the old errors I fixed enabled data transformations to occur which were originally stopped by the blocking in stage 1.

Please ask if you would like the whole printout, I only provide the most relevant printout below.

The following is the printout from `run.neighborhoods.py`, and the specific error comes from the assertion that the dataframe maintains its original shape on line 448; this is all being run on the example data embedded in this repository.

Thank you very much for your help, and I look forward to eliminating these bugs.

`run.neighborhoods.py ~>`
```
Running command: bedtools sort -faidx /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/reference/chr22 -i /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Neighborhoods/GeneList.TSS1kb.bed > /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Neighborhoods/GeneList.TSS1kb.bed.sorted; mv /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Neighborhoods/GeneList.TSS1kb.bed.sorted /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Neighborhoods/GeneList.TSS1kb.bed
    Loading coverage from pre-calculated file for Genes.H3K27ac.ENCFF384ZZM.chr22.bam
    Feature H3K27ac completed in 0.025640010833740234
    Loading coverage from pre-calculated file for Genes.DHS.wgEncodeUwDnaseK562AlnRep1.chr22.bam
    Loading coverage from pre-calculated file for Genes.DHS.wgEncodeUwDnaseK562AlnRep2.chr22.bam
    Feature DHS completed in 0.0519099235534668
    Loading coverage from pre-calculated file for Genes.TSS1kb.H3K27ac.ENCFF384ZZM.chr22.bam
    Feature H3K27ac completed in 0.024033546447753906
    Loading coverage from pre-calculated file for Genes.TSS1kb.DHS.wgEncodeUwDnaseK562AlnRep1.chr22.bam
    Loading coverage from pre-calculated file for Genes.TSS1kb.DHS.wgEncodeUwDnaseK562AlnRep2.chr22.bam
    Feature DHS completed in 0.049674034118652344
    Loading coverage from pre-calculated file for Enhancers.H3K27ac.ENCFF384ZZM.chr22.bam
    Traceback (most recent call last):
    File "/alphabet/ABC-Enhancer-Gene-Prediction/src/run.neighborhoods.py", line 97, in <module>
        main(args)
    File "/alphabet/ABC-Enhancer-Gene-Prediction/src/run.neighborhoods.py", line 93, in main
        processCellType(args)
    File "/alphabet/ABC-Enhancer-Gene-Prediction/src/run.neighborhoods.py", line 88, in processCellType
        outdir = args.outdir)
    File "/alphabet/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 197, in load_enhancers
        enhancers = count_features_for_bed(enhancers, candidate_peaks, genome_sizes, features, outdir, "Enhancers", skip_rpkm_quantile, force, use_fast_count)
    File "/alphabet/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 415, in count_features_for_bed
        df = count_single_feature_for_bed(df, bed_file, genome_sizes, feature_bam, feature, directory, filebase, skip_rpkm_quantile, force, use_fast_count)
    File "/alphabet/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 448, in count_single_feature_for_bed
        assert df.shape[0] == orig_shape, "Dimension mismatch"
    AssertionError: Dimension mismatch
    exit status 1
```  

`neighborhoods.py ~>`
```
def count_single_feature_for_bed(df, bed_file, genome_sizes, feature_bam, feature, directory, filebase, skip_rpkm_quantile, force, use_fast_count):
    orig_shape = df.shape[0]
    feature_name = feature + "." + os.path.basename(feature_bam)
    feature_outfile = os.path.join(directory, "{}.{}.CountReads.bedgraph".format(filebase, feature_name))

    if force or (not os.path.exists(feature_outfile)) or (os.path.getsize(feature_outfile) == 0):
        print("Regenerating", feature_outfile)
        print("Counting coverage for {}".format(filebase + "." + feature_name))
        run_count_reads(feature_bam, feature_outfile, bed_file, genome_sizes, use_fast_count)
    else:
        print("Loading coverage from pre-calculated file for {}".format(filebase + "." + feature_name))

    domain_counts = read_bed(feature_outfile)
    score_column = domain_counts.columns[-1]

    total_counts = count_total(feature_bam)

    domain_counts = domain_counts[['chr', 'start', 'end', score_column]]
    featurecount = feature_name + ".readCount"
    domain_counts.rename(columns={score_column: featurecount}, inplace=True)
    domain_counts['chr'] = domain_counts['chr'].astype('str')

    df = df.merge(domain_counts.drop_duplicates())
    #df = smart_merge(df, domain_counts.drop_duplicates())

    assert df.shape[0] == orig_shape, "Dimension mismatch" ### Line 448 ###

    df[feature_name + ".RPM"] = 1e6 * df[featurecount] / float(total_counts)

    if not skip_rpkm_quantile:
        df[featurecount + ".quantile"] = df[featurecount].rank() / float(len(df))
        df[feature_name + ".RPM.quantile"] = df[feature_name + ".RPM"].rank() / float(len(df))
        df[feature_name + ".RPKM"] = 1e3 * df[feature_name + ".RPM"] / (df.end - df.start).astype(float)
        df[feature_name + ".RPKM.quantile"] = df[feature_name + ".RPKM"].rank() / float(len(df))

    return df[~ df.duplicated()]

def average_features(df, feature, feature_bam_list, skip_rpkm_quantile):
    feature_RPM_cols = [feature + "." + os.path.basename(feature_bam) + '.RPM' for feature_bam in feature_bam_list]

    df[feature + '.RPM'] = df[feature_RPM_cols].mean(axis = 1)
    
    if not skip_rpkm_quantile:
        feature_RPKM_cols = [feature + "." + os.path.basename(feature_bam) + '.RPKM' for feature_bam in feature_bam_list]
        df[feature + '.RPM.quantile'] = df[feature + '.RPM'].rank() / float(len(df))
        df[feature + '.RPKM'] = df[feature_RPKM_cols].mean(axis = 1)
        df[feature + '.RPKM.quantile'] = df[feature + '.RPKM'].rank() / float(len(df))

    return df
```

**Comment by neekonsu** [comment]
@jnasser3 I have been doing some poking around in the stack trace to no avail, but I have an idea.

If you or one of your team members could drop the pipeline inside of a Docker container and get the pipeline to work properly on the example code, that would both help my cause (writing an abstraction of this pipeline) as well as others who might run into the same trouble.

I would be willing to help in the process, you can always reach my at my email `neekonsu@gmail.com`

Thank you

**Comment by thouis** [comment]
I wonder if this is an error in the precalculated files.  Could you check the contents of …/Neighborhoods/Enhancers.H3K27ac*?  How many lines does it have, vs how many are there in EnhancerList.bed?

You might also remove all the precalculated files and re-run.

**Comment by thouis** [comment]
I've just added a branch `use_pysam` that you might check out and see if it addresses this crash.  I'll also look into putting the code into a docker container.

**Comment by neekonsu** [comment]
Hi @thouis, thank you for the suggestions, I will look into the precalculated files and let you know if they are the root cause.

I will also try `use_pysam`, thank you for your help. I will try all of this out tomorrow and let you know.

**Comment by neekonsu** [comment]
Hi @thouis , here is what I see examining the file:

```
/ABC-Enhancer-Gene-Prediction# ls -n example_chr22/ABC_output/Neighborhoods/
total 2080
-rw-r--r-- 1 0 0  187561 Sep 23 04:24 EnhancerList.bed
-rw-r--r-- 1 0 0 1208605 Sep 23 04:24 EnhancerList.txt
-rw-r--r-- 1 0 0   90169 Sep 23 04:24 Enhancers.DHS.wgEncodeUwDnaseK562AlnRep1.chr22.bam.CountReads.bedgraph
-rw-r--r-- 1 0 0   89759 Sep 23 04:24 Enhancers.DHS.wgEncodeUwDnaseK562AlnRep2.chr22.bam.CountReads.bedgraph
-rw-r--r-- 1 0 0   87932 Sep 23 04:24 Enhancers.H3K27ac.ENCFF384ZZM.chr22.bam.CountReads.bedgraph
-rw-r--r-- 1 0 0   19707 Sep 23 04:26 GeneList.TSS1kb.bed
-rw-r--r-- 1 0 0   19707 Sep 23 04:26 GeneList.bed
-rw-r--r-- 1 0 0  313206 Sep 23 04:26 GeneList.txt
-rw-r--r-- 1 0 0   15421 Sep 23 04:24 Genes.DHS.wgEncodeUwDnaseK562AlnRep1.chr22.bam.CountReads.bedgraph
-rw-r--r-- 1 0 0   15390 Sep 23 04:24 Genes.DHS.wgEncodeUwDnaseK562AlnRep2.chr22.bam.CountReads.bedgraph
-rw-r--r-- 1 0 0   15291 Sep 23 04:24 Genes.H3K27ac.ENCFF384ZZM.chr22.bam.CountReads.bedgraph
-rw-r--r-- 1 0 0   15065 Sep 23 04:24 Genes.TSS1kb.DHS.wgEncodeUwDnaseK562AlnRep1.chr22.bam.CountReads.bedgraph
-rw-r--r-- 1 0 0   15043 Sep 23 04:24 Genes.TSS1kb.DHS.wgEncodeUwDnaseK562AlnRep2.chr22.bam.CountReads.bedgraph
-rw-r--r-- 1 0 0   14882 Sep 23 04:24 Genes.TSS1kb.H3K27ac.ENCFF384ZZM.chr22.bam.CountReads.bedgraph
```

I `cat` the following contents from `Enhancers.H3K27ac.ENCFF384ZZM.chr22.bam.CountReads.bedgraph`:

```
chr22   50639095        50639657        11
chr22   50657752        50658252        1
chr22   50679482        50679982        6
chr22   50683150        50683765        85
chr22   50688765        50689265        19
chr22   50689422        50690084        12
chr22   50691887        50692387        1
chr22   50699344        50699844        34
chr22   50699989        50700568        6
chr22   50700814        50701314        18
chr22   50707979        50708479        5
chr22   50708572        50709356        5
chr22   50710027        50710527        1
chr22   50742861        50743361        6
```
The dimensions also seem consistent through the file, so our error of dimensionality does not seem to come from artifacting.

**Comment by neekonsu** [comment]
I checked out the `use_pysam` branch and installed `pysam` to test out the branch, but unfortunately the same error persisted:

```
Loading coverage from pre-calculated file for Enhancers.H3K27ac.ENCFF384ZZM.chr22.bam
Traceback (most recent call last):
  File "src/run.neighborhoods.py", line 97, in <module>
    main(args)
  File "src/run.neighborhoods.py", line 93, in main
    processCellType(args)
  File "src/run.neighborhoods.py", line 88, in processCellType
    outdir = args.outdir)
  File "/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 198, in load_enhancers
    enhancers = count_features_for_bed(enhancers, candidate_peaks, genome_sizes, features, outdir, "Enhancers", skip_rpkm_quantile, force, use_fast_count)
  File "/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 361, in count_features_for_bed
    df = count_single_feature_for_bed(df, bed_file, genome_sizes, feature_bam, feature, directory, filebase, skip_rpkm_quantile, force, use_fast_count)
  File "/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 394, in count_single_feature_for_bed
    assert df.shape[0] == orig_shape, "Dimension mismatch"
```

**Comment by thouis** [comment]
It looks like it's using an existing .bedgraph file instead of recalculating.  Could you remove *.bedgraph in the Neighborhoods subdirectory and re-run with the pysam branch?

**Comment by neekonsu** [comment]
So I observe the following new behavior after deleting `./Neighborhoods/*.bedgraph`.
It seems that the dimensionality assertion no longer throws its error, and there is a large portion of added printout that was missing before.
You will see that an error I had previously asked about comes back, which is Bedtools claiming to be unable to process the input files.
The new error sounds like something fairly simple -- a possible edge case in index selection or something of the sort -- but I have not had the time to trace back the error yet.

Here is the printout, this is progress from before:

```
Running: awk 'FNR==NR {x2[$1] = $0; next} $1 in x2 {print x2[$1]}' /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/reference/chr22 <(samtools view -H /labs/mpsnyder/neekonsu/202
_chr22/input_data/Chromatin/wgEncodeUwDnaseK562AlnRep1.chr22.bam | grep SQ | cut -f 2 | cut -c 4- )  > /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Peaks/wgEncodeU
sorted.wgEncodeUwDnaseK562AlnRep1.chr22.bam.Counts.bed.temp_sort_order
Running: bedtools sort -faidx /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Peaks/wgEncodeUwDnaseK562AlnRep1.chr22.macs2_peaks.narrowPeak.sorted.wgEncodeUwDnaseK562
 /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Peaks/wgEncodeUwDnaseK562AlnRep1.chr22.macs2_peaks.narrowPeak.sorted | bedtools coverage -g /labs/mpsnyder/neekonsu/2
le_chr22/ABC_output/Peaks/wgEncodeUwDnaseK562AlnRep1.chr22.macs2_peaks.narrowPeak.sorted.wgEncodeUwDnaseK562AlnRep1.chr22.bam.Counts.bed.temp_sort_order -counts -sorted -a stdin -b /
hr22/input_data/Chromatin/wgEncodeUwDnaseK562AlnRep1.chr22.bam | awk '{print $1 "\t" $2 "\t" $3 "\t" $NF}'  | bedtools sort -faidx /alphabet/ABC-Enhancer-Gene-Prediction/example_chr2
konsu/2020/alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Peaks/wgEncodeUwDnaseK562AlnRep1.chr22.macs2_peaks.narrowPeak.sorted.wgEncodeUwDnaseK562AlnRep1.chr22.bam.Counts.bed; rm /labs/mpsnyder/
tion/example_chr22/ABC_output/Peaks/wgEncodeUwDnaseK562AlnRep1.chr22.macs2_peaks.narrowPeak.sorted.wgEncodeUwDnaseK562AlnRep1.chr22.bam.Counts.bed.temp_sort_order
Fast count method failed to count: /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/input_data/Chromatin/wgEncodeUwDnaseK562AlnRep1.chr22.bam


Trying bamtobed method ...

Running: bedtools bamtobed -i /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/input_data/Chromatin/wgEncodeUwDnaseK562AlnRep1.chr22.bam | cut -f 1-3 | bedtools intersect -wa -a
ABC-Enhancer-Gene-Prediction/example_chr22/reference/chr22.bed | bedtools sort -i stdin -faidx /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/reference/chr22 | bedtools coverag
Enhancer-Gene-Prediction/example_chr22/reference/chr22 -counts -sorted -a /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Peaks/wgEncodeUwDnaseK562AlnRep1.chr22.macs2
 $1 "\t" $2 "\t" $3 "\t" $NF}' > /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Peaks/wgEncodeUwDnaseK562AlnRep1.chr22.macs2_peaks.narrowPeak.sorted.wgEncodeUwDnaseK
No columns to parse from file
b''
BEDTools failed to count file: /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/input_data/Chromatin/wgEncodeUwDnaseK562AlnRep1.chr22.bam

#################################################################
############# Good printout from intermediate steps #############
#################################################################

Confirming inputs for 'predict.py':
——————————————————————
/alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Neighborhoods/EnhancerList.txt
example_chr22/ABC_output/Neighborhoods/EnhancerList.txt
——————————————————————
/alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Neighborhoods/GeneList.txt
example_chr22/ABC_output/Neighborhoods/GeneList.txt
——————————————————————
/alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/input_data/Chromatin/../HiC/raw/
example_chr22/input_data/HiC/raw/
——————————————————————
5000
5000
——————————————————————
K562
K562
——————————————————————
/alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Predictions/
example_chr22/ABC_output/Predictions/
——————————————————————
reading genes
reading enhancers
Making predictions for chromosome: chr22
Making putative predictions table...
Using: /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/input_data/Chromatin/../HiC/raw/chr22/chr22.KRobserved.gz
Begin HiC
Loading HiC
hic.to.sparse: Elapsed time: 0.8096952438354492
HiC Matrix has row sums of 2462.539801718806, making doubly stochastic...
HiC has 1479373 rows after windowing between 0 and 5000000
process.hic: Elapsed time: 1.7739653587341309
HiC added to predictions table. Elapsed time: 0.3026614189147949
HiC Complete
Completed chromosome: chr22. Elapsed time: 3.255986452102661

Writing output files...
Traceback (most recent call last):
  File "/alphabet/ABC-Enhancer-Gene-Prediction/src/predict.py", line 148, in <module>
    main()
  File "/alphabet/ABC-Enhancer-Gene-Prediction/src/predict.py", line 125, in main
    make_gene_prediction_stats(all_putative, args)
  File "/alphabet/ABC-Enhancer-Gene-Prediction/src/predictor.py", line 197, in make_gene_prediction_stats
    summ1 = summ1.merge(summ2, left_index=True, right_index=True)
  File "/home/neekonsu/.conda/envs/abc/lib/python3.6/site-packages/pandas/core/frame.py", line 7956, in merge
    validate=validate,
  File "/home/neekonsu/.conda/envs/abc/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 89, in merge
    return op.get_result()
  File "/home/neekonsu/.conda/envs/abc/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 668, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/home/neekonsu/.conda/envs/abc/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 872, in _get_join_info
    right_ax, how=self.how, return_indexers=True, sort=self.sort
  File "/home/neekonsu/.conda/envs/abc/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3440, in join
    return self._join_multi(other, how=how, return_indexers=return_indexers)
  File "/home/neekonsu/.conda/envs/abc/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3542, in _join_multi
    raise ValueError("cannot join with no overlapping index names")
ValueError: cannot join with no overlapping index names
exit status 1
```

**Comment by thouis** [comment]
That's very strange.  

Could you add a line to https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/blob/master/src/predictor.py#L191 just before the merge printing out summ1.head() and summ2.head()?  I can't see how these would have non-overlapping indices.

It looks like the full prediction file should have written by this point.  Do you see it in your output?

**Comment by neekonsu** [comment]
I will try printing out the final summ's from `predictor.py`. My system is having some problems running properly, so I will get back to you with results as soon as I get the environment back up.

**Comment by neekonsu** [comment]
Ok, so I have some interesting results. I was running into far to many dependency issues trying to run the pipeline plainly on our shared cluster, so I decided to get back inside of the docker environment from [alphabet](https://github.com/neekonsu/alphabet). In a previous issue, I discussed how using `makeCandidateRegions.py` would invoke errors saying that the input files could not be read/parsed, but when I executed the commands directly as they were printed out in the console, no errors were thrown. 

I noticed that in the times I ran the pipeline and got the index errors mentioned above, I was also using `makeCandidateRegions.py` and getting the same error from long before, and I think that somehow led to cascading effects in the pipeline. Running those segments by hand yields no errors and gets output in the last stage without the `no overlapping index names` error as well.

At some point a while ago, I remember patching the `makeCandidateRegions.py` malfunction by changing one of the last parser arguments to `default="True"`, but I cannot remember which and will need to do further testing.

Now that this runs all the way through, I am concerned that my fix is only patching the symptoms of the error. I cannot tell why `makeCandidateRegions.py` does not function while executing its child commands manually does properly function. There is a long stack that I had trouble following, so I cannot tell if those shell commands are all that `makeCandidateRegions` executes; if that is all, then I am happy using my manual work-around.

Interestingly, while everything executes, I do get some interesting warnings from `predict.py`:

```
reading genes
reading enhancers
Making predictions for chromosome: chr22
Making putative predictions table...
Using: /alphabet/ABC-Enhancer-Gene-Prediction/example_chr22/input_data/Chromatin/../HiC/raw/chr22/chr22.KRobserved.gz
Begin HiC
Loading HiC
hic.to.sparse: Elapsed time: 0.4300343990325928
HiC Matrix has row sums of 2462.539801718806, making doubly stochastic...
**/alphabet/ABC-Enhancer-Gene-Prediction/src/hic.py:141: RuntimeWarning: invalid value encountered in less
  norms[norms < kr_cutoff] = np.nan
/alphabet/ABC-Enhancer-Gene-Prediction/src/hic.py:142: RuntimeWarning: invalid value encountered in greater_equal
  norms[norms >= kr_cutoff] = 1**
HiC has 1479373 rows after windowing between 0 and 5000000
process.hic: Elapsed time: 0.6265480518341064
HiC added to predictions table. Elapsed time: 0.3388533592224121
HiC Complete
Completed chromosome: chr22. Elapsed time: 2.0410852432250977 
```

Please let me know what thoughts you have on working around the error in makeCandidateRegions, and I look forward to reaching a solution!

**Comment by thouis** [comment]
Which branch is the docker running?

**Comment by neekonsu** [comment]
Hey, docker is running the master branch of `Alphabet`, which implements the master branch of `ABC-Enhancer-Gene-Prediction`

**Comment by thouis** [comment]
Can it be moved to the use_pysam branch?

**Comment by neekonsu** [comment]
Yes, let me checkout the branch and let you know how it behaves

**Comment by Andi964** [comment]
Hello,

were you able to solve this issue? I get it with the most recent abc version, too.

Best
Andreas

**Comment by neekonsu** [comment]
I don't believe I resolved this issue. I moved on and wrote case-specific scripts as a workaround. Good luck @Andi964

**Comment by sakuramaezonoYCU** [comment]
I am getting the same error with the latest master branch. Has anyone successfully debugged the issue?

**Comment by atancoder** [comment]
We've revamped the codebase. Please check out https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/tree/main and reopen your issue if it still exists
