### ISSUE TITLE
Syntax Error while running MakeCandidateRegions.py

### ISSUE THREAD

**Issue by londonlondon20** [broadinstitute/ABC-Enhancer-Gene-Prediction#33]
Hello,

As per the documentation, I have been running the following command. However, I keep getting a "syntax" error. Would appreciate any advice. 

python src/makeCandidateRegions.py \
> --narrowPeak D15_rep1_atac.macs2_peaks.narrowPeak.sorted \
> --bam D15_rep1_atac.bam \
> --outDir /Output/ \
> --chrom_sizes chr.txt \
> --regions_blacklist wgEncodeHg19ConsensusSignalArtifactRegions.bed \
> --regions_whitelist RefSeqGeneBounds.txt \
> --peakExtendFromSummit 250 \
> --nStrongestPeaks 150000
Traceback (most recent call last):
  File "src/makeCandidateRegions.py", line 5, in <module>
    from peaks import *
  File "ABC-Enhancer-Gene-Prediction-0.2.2/src/peaks.py", line 5, in <module>
    from tools import *
  File "src/tools.py", line 7, in <module>
    import pyranges as pr
  File "lib/python2.7/site-packages/pyranges/__init__.py", line 16, in <module>
    import pyranges as pr
  File "lib/python2.7/site-packages/pyranges/pyranges.py", line 3272
    def print(self, n=8, merge_position=False, sort=False, formatting=None, chain=False):
            ^
SyntaxError: invalid syntax

**Comment by thouis** [comment]
This looks like an error in pyranges.  Which version did you install?

**Comment by londonlondon20** [comment]
Thanks, issue resolved.
