### ISSUE TITLE
error in run.neighborhoods.py

### ISSUE THREAD

**Issue by Rhine86** [broadinstitute/ABC-Enhancer-Gene-Prediction#38]
Hi, when I run run.neighborhoods.py, I encounter errors shown as below. Can you help me findout where is the problem? Thank you very much.
"Assigning classes to enhancers
Traceback (most recent call last):
  File "/home/yzhang/Software/ABC-Enhancer-Gene-Prediction-master/src/run.neighborhoods.py", line 97, in <module>
    main(args)
  File "/home/yzhang/Software/ABC-Enhancer-Gene-Prediction-master/src/run.neighborhoods.py", line 93, in main
    processCellType(args)
  File "/home/yzhang/Software/ABC-Enhancer-Gene-Prediction-master/src/run.neighborhoods.py", line 88, in processCellType
    outdir = args.outdir)
  File "/home/yzhang/Software/ABC-Enhancer-Gene-Prediction-master/src/neighborhoods.py", line 206, in load_enhancers
    enhancers = assign_enhancer_classes(enhancers, genes, tss_slop = tss_slop_for_class_assignment)
  File "/home/yzhang/Software/ABC-Enhancer-Gene-Prediction-master/src/neighborhoods.py", line 248, in assign_enhancer_classes
    genes, promoters = get_class_pyranges(enh)
  File "/home/yzhang/Software/ABC-Enhancer-Gene-Prediction-master/src/neighborhoods.py", line 235, in get_class_pyranges
    promoter_enh = promoter_enh.df[['symbol','uid']].groupby('uid',as_index=False).aggregate(lambda x: ','.join(list(set(x))))
  File "/home/yzhang/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2908, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/yzhang/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/home/yzhang/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1298, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['symbol', 'uid'], dtype='object')] are in the [columns]"
"

My command is 
"python ~/Software/ABC-Enhancer-Gene-Prediction-master/src/run.neighborhoods.py --ATAC ATAC.rmdup.bam  --candidate_enhancer_regions ABC_output/Peaks/enhancer.narrowPeak.candidateRegions.bed --genes mm9.bed   --H3K27ac WT-H3K27ac.bam --expression_table WT.TPM.txt --chrom_sizes mm9.chrom.sizes  --outdir ABC_output/Neighborhoods/"

**Comment by thouis** [comment]
Can you check the content of enhancer.narrowPeak.candidateRegions.bed?  Is it empty?

Also, could you put that enhancers file, as well as your mm9.bed and mm9.chrom.sizes file somewhere online that I can download?  I can test using them.

**Comment by Rhine86** [comment]
> Can you check the content of enhancer.narrowPeak.candidateRegions.bed? Is it empty?
> 
> Also, could you put that enhancers file, as well as your mm9.bed and mm9.chrom.sizes file somewhere online that I can download? I can test using them.

Hi, I have put those three files on http://159.226.118.202/public/yzhang/For_ABC/. Thanks.

**Comment by thouis** [comment]
I think I've found the problem - there don't seem to be any overlaps between enhancers and the promoters in your gene list.  I've added code to the `no_promoter_overlaps` branch.  Could you check if that branch works for your data?

(That branch is based on the `use_pysam` branch, so you may have to install pysam as well.)

**Comment by Rhine86** [comment]
> I think I've found the problem - there don't seem to be any overlaps between enhancers and the promoters in your gene list. I've added code to the `no_promoter_overlaps` branch. Could you check if that branch works for your data?
> 
> (That branch is based on the `use_pysam` branch, so you may have to install pysam as well.)

Yes, when defining enhancers, I remove those have overlaps with promoters. It works now. Thank you.
