### ISSUE TITLE
predict.py trouble reading bampe

### ISSUE THREAD

**Issue by connorrogerson** [broadinstitute/ABC-Enhancer-Gene-Prediction#41]
I'm currently trying to run predict.py. I have HiC in BAMPE format in one file. It seems the code is trying to look for files per chromosome rather than a single file?

Command: 
`python /home/cjr78/packages/ABC-Enhancer-Gene-Prediction-no_promoter_overlaps/src/predict.py \
--enhancers /rds/user/cjr78/hpc-work/HiC/ABC/Neighborhoods/FlFl/EnhancerList.txt \
--genes /rds/user/cjr78/hpc-work/HiC/ABC/Neighborhoods/FlFl/GeneList.txt \
--HiCdir /rds/user/cjr78/hpc-work/HiC/BAMPE/raw/FlFl/ \
--hic_type bedpe \
--hic_resolution 40000 \
--scale_hic_using_powerlaw \
--threshold .02 \
--cellType FlFl \
--outdir /rds/user/cjr78/hpc-work/HiC/ABC/Predict/FlFl/ \
--make_all_putative`

Error:
`reading genes
reading enhancers
Making predictions for chromosome: chr7
Making putative predictions table...
Begin HiC
Loading HiC
Traceback (most recent call last):
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-no_promoter_overlaps/src/predict.py", line 148, in <module>
    main()
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-no_promoter_overlaps/src/predict.py", line 107, in main
    this_chr = make_predictions(chromosome, this_enh, this_genes, args)
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-no_promoter_overlaps/src/predictor.py", line 17, in make_predictions
    pred = add_hic_to_enh_gene_table(enhancers, genes, pred, hic_file, hic_norm_file, hic_is_vc, chromosome, args)
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-no_promoter_overlaps/src/predictor.py", line 66, in add_hic_to_enh_gene_table
    gamma = args.hic_gamma)
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-no_promoter_overlaps/src/hic.py", line 55, in load_hic
    HiC = pd.read_csv(hic_file, sep="\t", names = ['chr1','x1','x2','chr2','y1','y2','name','hic_contact'])
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 613, in pandas._libs.parsers.TextReader._setup_parser_source
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/rds/user/cjr78/hpc-work/HiC/BAMPE/raw/FlFl/chr7/chr7.bedpe.gz'
`

**Comment by thouis** [comment]
Based on the code for [get_hic_file](https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/blob/8cde9c3ee62ed1589afc18a25f45da35f0473205/src/hic.py#L6), it does look like it needs to be separated by chromosome.  You could do that using grep, or possibly just create several symbolic links to the same file with different chromosome names.

**Comment by connorrogerson** [comment]
So I've split my HiC files by chromosome and the code runs, however I've run into a new problem. It seems when the tool is reading chr1 it gives this error:

##
reading genes
reading enhancers
Making predictions for chromosome: chr2
Making putative predictions table...
Begin HiC
Loading HiC
HiC added to predictions table. Elapsed time: 23.225021600723267
HiC Complete
Completed chromosome: chr2. Elapsed time: 26.475627183914185

Making predictions for chromosome: chr1
Making putative predictions table...
Begin HiC
Loading HiC
/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-no_promoter_overlaps/src/predict.py:107: DtypeWarning: Columns (1,2,4,5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  this_chr = make_predictions(chromosome, this_enh, this_genes, args)
Traceback (most recent call last):
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 149, in na_arithmetic_op
    result = expressions.evaluate(op, str_rep, left, right)
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 208, in evaluate
    return _evaluate(op, op_str, a, b)
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 70, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-no_promoter_overlaps/src/predict.py", line 148, in <module>
    main()
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-no_promoter_overlaps/src/predict.py", line 107, in main
    this_chr = make_predictions(chromosome, this_enh, this_genes, args)
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-no_promoter_overlaps/src/predictor.py", line 17, in make_predictions
    pred = add_hic_to_enh_gene_table(enhancers, genes, pred, hic_file, hic_norm_file, hic_is_vc, chromosome, args)
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-no_promoter_overlaps/src/predictor.py", line 81, in add_hic_to_enh_gene_table
    hic1 = df_to_pyranges(HiC, start_col='x1', end_col='x2', chr_col='chr1')
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-no_promoter_overlaps/src/tools.py", line 53, in df_to_pyranges
    df['Start'] = df[start_col] - start_slop
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/core/ops/common.py", line 64, in new_method
    return method(self, other)
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 503, in wrapper
    result = arithmetic_op(lvalues, rvalues, op, str_rep)
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 197, in arithmetic_op
    res_values = na_arithmetic_op(lvalues, rvalues, op, str_rep)
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 151, in na_arithmetic_op
    result = masked_arith_op(left, right, op)
  File "/home/cjr78/.conda/envs/seq_analysis/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 112, in masked_arith_op
    result[mask] = op(xrav[mask], y)
TypeError: unsupported operand type(s) for -: 'str' and 'int'
##

I've tried running it twice and it always errors n chr1.

**Comment by thouis** [comment]
Could you send me your chr1 HiC file?  (thouis at broadinstitute.org)

I expect this is a quick fix, but it would be useful to be able to test it on the actual file.

**Comment by connorrogerson** [comment]
Worked out my own problem - the error above is because the header of the file was being printed in the chr1 file. Removing the header solved the error.

**Comment by connorrogerson** [comment]
One questions is do the HiC files need to be kr normalised are do they need to be raw counts?

**Comment by thouis** [comment]
I believe the code will automatically normalize the HiC if needed.

**Comment by jn21** [comment]
The code does not KR normalize HiC files provided in BEDPE format - (it only KR normalizes for HiC files in 'juicebox' format (three column adjacency matrix format)). 

This is because the BEDPE format is designed to allow passing in Contact data that does not conform to a matrix - for example: Contact data at multiple different resolutions, at non-equally spaced bins, or contact data in which not the entire matrix is known (eg, from promoter capture experiments). For such data the concept of KR normalization is not defined.
