### ISSUE TITLE
ValueError in compute_powerlaw_fit_from_hic.py with BEDPE file

### ISSUE THREAD

**Issue by yasumasak** [broadinstitute/ABC-Enhancer-Gene-Prediction#50]
Hi,
I encountered an error while running 'compute_powerlaw_fit_from_hic.py' for BEDPE Hi-C contact file: 
```
Invalid file path or buffer object type: <class 'tuple'>
Traceback (most recent call last):
  File "/home/fgprgn/tools/ABC-Enhancer-Gene-Prediction/src/compute_powerlaw_fit_from_hic.original.py", line 76, in load_hic_for_powerlaw
    this_data = load_hic(hic_file = hic_file,
  File "/yshare2/ZETTAI_path_WA_slash_home_KARA/home/fgprgn/tools/ABC-Enhancer-Gene-Prediction/src/hic.py", line 55, in load_hic
    HiC = pd.read_csv(hic_file, sep="\t", names = ['chr1','x1','x2','chr2','y1','y2','name','hic_contact'])
  File "/home/fgprgn/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/fgprgn/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 434, in _read
    fp_or_buf, _, compression, should_close = get_filepath_or_buffer(
  File "/home/fgprgn/anaconda3/lib/python3.8/site-packages/pandas/io/common.py", line 243, in get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'tuple'>
```
I just solved this by modifying line 74 as below.
`hic_file, hic_norm_file, hic_is_vc = get_hic_file(chrom, args.hicDir, hic_type='bedpe')`

**Comment by thouis** [comment]
Thanks, I've committed a fix for this.
