### ISSUE TITLE
Value error problem in the predict.py step of the pipeline

### ISSUE THREAD

**Issue by manueltar** [broadinstitute/ABC-Enhancer-Gene-Prediction#59]
Hi,

First of all, thank you for developing the software, the repository and writing the documentation, and, also thank you for the support. We are trying to run the AbC enhancer prediction in the cluster of the Sanger Institute. We have installed the different dependencies and we are able to run the pipeline up to the last step, the predict step. I have checked the issues reported and I have none that matches the error we have:

```
$ python /nfs/team151/software/AbC_scores/ABC-Enhancer-Gene-Prediction/src/predict.py --enhancers /nfs/team151/software/AbC_scores/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Neighborhoods/EnhancerList.txt --genes /nfs/team151/software/AbC_scores/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Neighborhoods/GeneList.txt --chrom_sizes /nfs/team151/software/AbC_scores/ABC-Enhancer-Gene-Prediction/example_chr22/reference/chr22 --HiCdir /nfs/team151/software/AbC_scores/ABC-Enhancer-Gene-Prediction/example_chr22/input_data/HiC/raw/ --hic_resolution 5000 --scale_hic_using_powerlaw --threshold .02 --cellType K562 --outdir /nfs/team151/software/AbC_scores/ABC-Enhancer-Gene-Prediction/example_chr22/ABC_output/Predictions/ --make_all_putative


reading genes
reading enhancers
Making predictions for chromosome: chr22
Making putative predictions table...
Using: /nfs/team151/software/AbC_scores/ABC-Enhancer-Gene-Prediction/example_chr22/input_data/HiC/raw/chr22/chr22.KRobserved.gz
Begin HiC
Loading HiC
hic.to.sparse: Elapsed time: 4.214726209640503
HiC Matrix has row sums of 2462.539801718806, making doubly stochastic...
HiC has 1479373 rows after windowing between 0 and 5000000
process.hic: Elapsed time: 3.5757029056549072
HiC added to predictions table. Elapsed time: 0.315493106842041
HiC Complete
Completed chromosome: chr22. Elapsed time: 9.790779829025269

Writing output files...
Traceback (most recent call last):
  File "/nfs/team151/software/AbC_scores/ABC-Enhancer-Gene-Prediction/src/predict.py", line 154, in <module>
    main()
  File "/nfs/team151/software/AbC_scores/ABC-Enhancer-Gene-Prediction/src/predict.py", line 129, in main
    make_gene_prediction_stats(all_putative, args)
  File "/nfs/team151/software/AbC_scores/ABC-Enhancer-Gene-Prediction/src/predictor.py", line 197, in make_gene_prediction_stats
    summ1 = summ1.merge(summ2, left_index=True, right_index=True)
  File "/software/hgi/installs/anaconda3/envs/hgi_base/lib/python3.7/site-packages/pandas/core/frame.py", line 7959, in merge
    validate=validate,
  File "/software/hgi/installs/anaconda3/envs/hgi_base/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 89, in merge
    return op.get_result()
  File "/software/hgi/installs/anaconda3/envs/hgi_base/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 668, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/software/hgi/installs/anaconda3/envs/hgi_base/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 872, in _get_join_info
    right_ax, how=self.how, return_indexers=True, sort=self.sort
  File "/software/hgi/installs/anaconda3/envs/hgi_base/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3446, in join
    return self._join_multi(other, how=how, return_indexers=return_indexers)
  File "/software/hgi/installs/anaconda3/envs/hgi_base/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3548, in _join_multi
    raise ValueError("cannot join with no overlapping index names")
ValueError: cannot join with no overlapping index names
```

Can you help us? Best regards,

**Comment by atancoder** [comment]
We've revamped the codebase. Please check out https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/tree/main and reopen your issue if it still exists
