### ISSUE TITLE
juicebox_dump.py

### ISSUE THREAD

**Issue by User-yx** [broadinstitute/ABC-Enhancer-Gene-Prediction#65]
Hi,
I want to use my own HiC data, I used juicer to convert the 7 columns of validpairs into a .hic file, but the error is reported as follows, what is the reason?
```
python ~/software/ABC-Enhancer-Gene-Prediction/src/juicebox_dump.py \
> --hic_file ~/01.data/11.HiC/01.PAM/16075_format_AllValidPairs.hic \
> --juicebox "java -jar ~/software/juicer_tools_1.22.01.jar" \
> --outdir ./raw/ \
>  --chromosomes 1
Starting chr1 ...
java -jar ~/software/juicer_tools_1.22.01.jar dump observed KR ~/01.data/11.HiC/01.PAM/16075_format_AllValidPairs.hic 1 1 BP 5000 ./raw//chr1//chr1.KRobserved
Running command: gzip ./raw//chr1//chr1.KRobserved
gzip: ./raw//chr1//chr1.KRobserved: No such file or directory
Traceback (most recent call last):
  File "~/software/ABC-Enhancer-Gene-Prediction/src/juicebox_dump.py", line 54, in <module>
    main(args)
  File "~/software/ABC-Enhancer-Gene-Prediction/src/juicebox_dump.py", line 35, in main
    run_command("gzip {0}/chr{1}.KRobserved".format(outdir, chromosome))
  File "~/software/ABC-Enhancer-Gene-Prediction/src/tools.py", line 15, in run_command
    return check_call(command, shell=True, **args)
  File "~/software/miniconda3/envs/final-abc-env/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'gzip ./raw//chr1//chr1.KRobserved' returned non-zero exit status 1.
```
Thanks!

**Comment by liviu-** [comment]
I got the same error for `juicer_tools_1.22.01.jar` but it worked using `juicer_tools_1.19.02.jar`.

**Comment by atancoder** [comment]
We've revamped the codebase. Please check out https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/tree/main and reopen your issue if it still exists
