### ISSUE TITLE
assert df.shape[0] == orig_shape, "Dimension mismatch"

### ISSUE THREAD

**Issue by Andi964** [broadinstitute/ABC-Enhancer-Gene-Prediction#73]
Hello,
thanks for creating this useful tool :)
When I run through the pipeline, I get stuck with the following error (command and error shown):
```
python "$abc_path"run.neighborhoods.py \
--candidate_enhancer_regions "$canReg_path" \
--genes "$ref_path"RefSeqCurated.170308.bed.CollapsedGeneBounds.bed \
--H3K27ac "$bam_path_histone" \
--DHS "$bam_path_dnase" \
--chrom_sizes "$ref_path"chr_sizes \
--outdir "$enhAct_path"
```

```
Traceback (most recent call last):
  File "/mnt/storage3/users/ahschma1/software/ABC-Enhancer-Gene-Prediction/src/run.neighborhoods.py", line 97, in <module>
    main(args)
  File "/mnt/storage3/users/ahschma1/software/ABC-Enhancer-Gene-Prediction/src/run.neighborhoods.py", line 93, in main
    processCellType(args)
  File "/mnt/storage3/users/ahschma1/software/ABC-Enhancer-Gene-Prediction/src/run.neighborhoods.py", line 74, in processCellType
    outdir = args.outdir)
  File "/mnt/storage3/users/ahschma1/software/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 90, in annotate_genes_with_features
    genes = count_features_for_bed(genes, bounds_bed, genome_sizes, features, outdir, "Genes", force=force, use_fast_count=use_fast_count)
  File "/mnt/storage3/users/ahschma1/software/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 361, in count_features_for_bed
    df = count_single_feature_for_bed(df, bed_file, genome_sizes, feature_bam, feature, directory, filebase, skip_rpkm_quantile, force, use_fast_count)
  File "/mnt/storage3/users/ahschma1/software/ABC-Enhancer-Gene-Prediction/src/neighborhoods.py", line 394, in count_single_feature_for_bed
    assert df.shape[0] == orig_shape, "Dimension mismatch"
AssertionError: Dimension mismatch
```

I am using the most recent version of abc and load all required packages with conda.
How can I solve this?

Best
Andreas

**Comment by LarkDamer** [comment]
Hello, 

Just wondering how you overcame this error. I am running into the same thing. Thanks!
